version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      ### Boa prática, criar um script para ser executado automaticamente quando o coteiner é iniciado pela 1º vez ###
      - ./database/m2_webhoster.sql:/docker-entrypoint-initdb.d/m2_webhoster.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: webhoster
      MYSQL_PASSWORD: secret
  nodejs-server:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: ["./database/wait-for-it.sh", "mysql:3306", "--", "npm", "start"]
